import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(__dirname, "../../..");
const MD_PATH = resolve(__dirname, "../reference/model-classifications.md");
const JSON_PATH = resolve(__dirname, "../reference/model-classifications.json");

/**
 * Step 2 — Classification verification tests.
 * Validates that model-classifications.md and .json are consistent
 * with the known-good classification list.
 */
describe.skip("Step 2 — classification verification", () => {
  const KNOWN_TENANT_DIRECT = [
    "Agent",
    "AgentPermissionGrant",
    "ApprovalPolicy",
    "CompanyMission",
    "Department",
    "Goal",
    "HeartbeatConfig",
    "HeartbeatContext",
    "HeartbeatRun",
    "Invitation",
    "OrganizationMember",
    "PolicyDecision",
    "Template",
  ];

  const KNOWN_GLOBAL = [
    "User",
    "VerificationToken",
    "Skill",
    "Organization",
    "PipelineTemplate",
    "Account",
    "Session",
  ];

  const KNOWN_USER_OWNED = ["ApiKey", "CLIGeneration", "GoogleOAuthToken", "MCPServer"];
  const KNOWN_AMBIGUOUS = ["AuditLog"];

  it("model-classifications.md exists", () => {
    expect(existsSync(MD_PATH)).toBe(true);
  });

  it("model-classifications.json exists (generated by step1)", () => {
    expect(existsSync(JSON_PATH)).toBe(true);
  });

  it("JSON has all TENANT_DIRECT models", () => {
    if (!existsSync(JSON_PATH)) return;
    const data = JSON.parse(readFileSync(JSON_PATH, "utf-8")) as {
      models: Array<{ name: string; classification: string }>;
    };
    const directNames = data.models
      .filter((m) => m.classification === "TENANT_DIRECT")
      .map((m) => m.name);

    for (const name of KNOWN_TENANT_DIRECT) {
      expect(directNames, `${name} should be TENANT_DIRECT`).toContain(name);
    }
  });

  it("JSON has all GLOBAL models", () => {
    if (!existsSync(JSON_PATH)) return;
    const data = JSON.parse(readFileSync(JSON_PATH, "utf-8")) as {
      models: Array<{ name: string; classification: string }>;
    };
    const globalNames = data.models
      .filter((m) => m.classification === "GLOBAL")
      .map((m) => m.name);

    for (const name of KNOWN_GLOBAL) {
      expect(globalNames, `${name} should be GLOBAL`).toContain(name);
    }
  });

  it("USER_OWNED count is 4", () => {
    if (!existsSync(JSON_PATH)) return;
    const data = JSON.parse(readFileSync(JSON_PATH, "utf-8")) as {
      counts: Record<string, number>;
    };
    expect(data.counts["USER_OWNED"]).toBe(4);
  });

  it("AuditLog is AMBIGUOUS", () => {
    if (!existsSync(JSON_PATH)) return;
    const data = JSON.parse(readFileSync(JSON_PATH, "utf-8")) as {
      models: Array<{ name: string; classification: string }>;
    };
    const auditLog = data.models.find((m) => m.name === "AuditLog");
    expect(auditLog?.classification).toBe("AMBIGUOUS");
  });

  it("step2-classify.ts exits 0 when JSON matches reference", async () => {
    if (!existsSync(JSON_PATH)) return;
    const { execSync } = await import("node:child_process");
    expect(() =>
      execSync("pnpm tsx skills/rls-rollout/scripts/step2-classify.ts", {
        cwd: ROOT,
        encoding: "utf-8",
        stdio: "pipe",
      })
    ).not.toThrow();
  });
});
