/**
 * Quick-start script generator for CLI bridge packages (F5).
 *
 * Generates install.sh and Dockerfile after successful pipeline completion.
 * These files are appended to generatedFiles and shown in the FileViewer
 * under a dedicated "Quick Start" section.
 *
 * Scripts are pure string generation — no AI call required.
 */

type GeneratedFiles = Record<string, string>;
type Target = "python" | "typescript";

interface QuickStartContext {
  applicationName: string;
  target: Target;
}

/**
 * Generate install.sh and Dockerfile for the completed CLI bridge.
 * Files are merged into existingFiles in advance/route.ts on completion.
 */
export function generateQuickStartFiles(ctx: QuickStartContext): GeneratedFiles {
  const files: GeneratedFiles = {};
  const safeName = ctx.applicationName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

  files["install.sh"] =
    ctx.target === "python"
      ? generatePythonInstallScript(safeName, ctx.applicationName)
      : generateTypeScriptInstallScript(safeName, ctx.applicationName);

  files["Dockerfile"] =
    ctx.target === "python"
      ? generatePythonDockerfile(safeName, ctx.applicationName)
      : generateTypeScriptDockerfile(safeName, ctx.applicationName);

  return files;
}

function generatePythonInstallScript(safeName: string, displayName: string): string {
  return `#!/bin/bash
# Quick-start installer for ${displayName} MCP bridge (Python / FastMCP)
# Generated by Agent Studio CLI Generator
set -euo pipefail

APP_NAME="${safeName}"

echo "==> Installing \${APP_NAME} MCP Bridge..."

# Check Python 3.10+
if ! command -v python3 &>/dev/null; then
  echo "Error: Python 3.10+ is required. Install from https://python.org"
  exit 1
fi

PYTHON_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "    Python \${PYTHON_VER} detected"

REQUIRED_MAJOR=3
REQUIRED_MINOR=10
ACTUAL_MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
if [ "\${ACTUAL_MINOR}" -lt "\${REQUIRED_MINOR}" ]; then
  echo "Error: Python 3.\${REQUIRED_MINOR}+ required (found \${PYTHON_VER})"
  exit 1
fi

# Create virtual environment
if [ ! -d ".venv" ]; then
  echo "==> Creating virtual environment..."
  python3 -m venv .venv
fi

source .venv/bin/activate

echo "==> Installing dependencies..."
pip install -r requirements.txt --quiet --disable-pip-version-check

echo ""
echo "✓ \${APP_NAME} MCP Bridge installed successfully!"
echo ""
echo "To use with Claude Desktop, add this to your config"
echo "(~/.config/claude/claude_desktop_config.json on Linux/macOS,"
echo " %APPDATA%\\Claude\\claude_desktop_config.json on Windows):"
echo ""
cat <<JSON
{
  "mcpServers": {
    "\${APP_NAME}": {
      "command": "\$(pwd)/.venv/bin/python",
      "args": ["server.py"],
      "cwd": "\$(pwd)"
    }
  }
}
JSON
echo ""
echo "Then restart Claude Desktop to pick up the new server."
`;
}

function generateTypeScriptInstallScript(safeName: string, displayName: string): string {
  return `#!/bin/bash
# Quick-start installer for ${displayName} MCP bridge (TypeScript / Node.js MCP SDK)
# Generated by Agent Studio CLI Generator
set -euo pipefail

APP_NAME="${safeName}"

echo "==> Installing \${APP_NAME} MCP Bridge..."

# Check Node.js 18+
if ! command -v node &>/dev/null; then
  echo "Error: Node.js 18+ is required. Install from https://nodejs.org"
  exit 1
fi

NODE_VER=$(node -e 'process.stdout.write(process.version.slice(1).split(".")[0])')
echo "    Node.js v\${NODE_VER} detected"

if [ "\${NODE_VER}" -lt "18" ]; then
  echo "Error: Node.js 18+ required (found v\${NODE_VER})"
  exit 1
fi

echo "==> Installing dependencies..."
npm install --quiet

echo "==> Building TypeScript..."
npm run build

echo ""
echo "✓ \${APP_NAME} MCP Bridge installed successfully!"
echo ""
echo "To use with Claude Desktop, add this to your config"
echo "(~/.config/claude/claude_desktop_config.json on Linux/macOS,"
echo " %APPDATA%\\Claude\\claude_desktop_config.json on Windows):"
echo ""
cat <<JSON
{
  "mcpServers": {
    "\${APP_NAME}": {
      "command": "node",
      "args": ["dist/server.js"],
      "cwd": "\$(pwd)"
    }
  }
}
JSON
echo ""
echo "Then restart Claude Desktop to pick up the new server."
`;
}

function generatePythonDockerfile(safeName: string, displayName: string): string {
  return `# Dockerfile for ${displayName} MCP bridge (Python / FastMCP)
# Generated by Agent Studio CLI Generator

FROM python:3.11-slim

LABEL org.opencontainers.image.title="${safeName}-mcp-bridge"
LABEL org.opencontainers.image.description="MCP bridge for ${displayName} (Python FastMCP)"

WORKDIR /app

# Install dependencies first for better layer caching
COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy remaining source files
COPY . .

# MCP servers communicate via stdio — no exposed port needed
CMD ["python", "server.py"]
`;
}

function generateTypeScriptDockerfile(safeName: string, displayName: string): string {
  return `# Dockerfile for ${displayName} MCP bridge (TypeScript / Node.js MCP SDK)
# Generated by Agent Studio CLI Generator

FROM node:20-slim AS builder

WORKDIR /app

# Install dependencies first for better layer caching
COPY package.json package-lock.json* ./
RUN npm ci --quiet

# Copy source and build
COPY . .
RUN npm run build

# ── Runtime stage ──────────────────────────────────────────────────────────
FROM node:20-slim

LABEL org.opencontainers.image.title="${safeName}-mcp-bridge"
LABEL org.opencontainers.image.description="MCP bridge for ${displayName} (TypeScript MCP SDK)"

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# MCP servers communicate via stdio — no exposed port needed
CMD ["node", "dist/server.js"]
`;
}
