#!/usr/bin/env tsx
/**
 * step5-runbook.ts — Generate per-table rollback runbook.
 *
 * For each table with RLS applied in a given phase, produces a markdown
 * runbook section covering:
 *   - Pre-cutover checklist
 *   - Migration apply command
 *   - Verification queries
 *   - 4-layer rollback procedure
 *   - Layer 4 nuclear SQL
 *
 * Output:
 *   reference/runbook-phase{N}-production.md
 *
 * Usage:
 *   pnpm tsx skills/rls-rollout/scripts/step5-runbook.ts --phase=1
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../..");
const REF_DIR = resolve(__dirname, "../reference");

interface TableSpec {
  name: string;
  classification: string;
}

const PHASE_1_TABLES: TableSpec[] = [
  { name: "Agent", classification: "TENANT_DIRECT (isPublic)" },
  { name: "AgentPermissionGrant", classification: "TENANT_DIRECT" },
  { name: "ApprovalPolicy", classification: "TENANT_DIRECT" },
  { name: "CompanyMission", classification: "TENANT_DIRECT" },
  { name: "Department", classification: "TENANT_DIRECT" },
  { name: "Goal", classification: "TENANT_DIRECT" },
  { name: "HeartbeatConfig", classification: "TENANT_DIRECT" },
  { name: "HeartbeatContext", classification: "TENANT_DIRECT" },
  { name: "HeartbeatRun", classification: "TENANT_DIRECT" },
  { name: "Invitation", classification: "TENANT_DIRECT" },
  { name: "OrganizationMember", classification: "TENANT_DIRECT" },
  { name: "PolicyDecision", classification: "TENANT_DIRECT" },
  { name: "Template", classification: "TENANT_DIRECT (isPublic)" },
];

function tableSection(table: TableSpec, _phaseNum: number): string {
  const lower = table.name.toLowerCase();
  return `
### ${table.name} (${table.classification})

**Verify before applying:**
\`\`\`sql
-- Confirm no NULL organizationId
SELECT COUNT(*) FROM "${table.name}" WHERE "organizationId" IS NULL;
-- Expected: 0

-- Row count (for rollback time estimate)
SELECT COUNT(*) FROM "${table.name}";
\`\`\`

**Apply migration:**
\`\`\`bash
DATABASE_URL=$STAGING_URL pnpm prisma migrate deploy
# Verify: bash skills/rls-rollout/scripts/step0-preflight.sh
\`\`\`

**Post-apply verification:**
\`\`\`sql
-- RLS enabled
SELECT relrowsecurity, relforcerowsecurity
FROM pg_class WHERE relname = '${table.name}';
-- Expected: both = true

-- Policies created
SELECT policyname, cmd FROM pg_policies WHERE tablename = '${table.name}';
-- Expected: ${lower}_select, ${lower}_insert, ${lower}_update, ${lower}_delete

-- app_user has grants (not owner role)
SELECT grantee, privilege_type FROM information_schema.role_table_grants
WHERE table_name = '${table.name}' AND grantee = 'app_user';
\`\`\`

**Layer 4 rollback SQL (nuclear — run only if Layers 1-3 fail):**
\`\`\`sql
-- DANGER: removes all RLS from ${table.name}
DROP POLICY IF EXISTS ${lower}_select ON "${table.name}";
DROP POLICY IF EXISTS ${lower}_insert ON "${table.name}";
DROP POLICY IF EXISTS ${lower}_update ON "${table.name}";
DROP POLICY IF EXISTS ${lower}_delete ON "${table.name}";
ALTER TABLE "${table.name}" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "${table.name}" NO FORCE ROW LEVEL SECURITY;
\`\`\`
`;
}

function run(): void {
  const phaseArg = process.argv.find((a) => a.startsWith("--phase="))?.split("=")[1];

  if (!phaseArg) {
    console.error("Usage: --phase=1");
    process.exit(1);
  }

  const phaseNum = parseInt(phaseArg, 10);
  let tables: TableSpec[] = [];

  if (phaseNum === 1) {
    tables = PHASE_1_TABLES;
  } else {
    console.error(`Phase ${phaseNum} tables not yet defined in this script.`);
    console.error("Add them to PHASE_N_TABLES arrays and re-run.");
    process.exit(1);
  }

  const date = new Date().toISOString().slice(0, 10);
  const outFile = resolve(REF_DIR, `runbook-phase${phaseNum}-production.md`);

  const content = `# Phase ${phaseNum} Production Cutover Runbook

Generated by \`step5-runbook.ts\` on ${date}.
**Read the master cutover runbook first:** \`docs/_archive/rls-phase-1-cutover-runbook.md\`

## Pre-cutover checklist (T-24h)

- [ ] All Phase ${phaseNum} staging tests passing for ≥ 24h
- [ ] Railway DB snapshot taken (Railway → Postgres → Backups → Create)
- [ ] Sentry alert rule for "permission denied" configured
- [ ] \`RLS_ENFORCEMENT_ENABLED=false\` confirmed in Railway production env
- [ ] Team notified of cutover window

## Cutover window (off-hours, ~30 min)

\`\`\`bash
# 1. Confirm flag is off
echo "RLS_ENFORCEMENT_ENABLED=\${RLS_ENFORCEMENT_ENABLED}"
# Expected: false or unset

# 2. Apply migration (uses postgres superuser — bypasses RLS)
DATABASE_URL=$PROD_DATABASE_URL pnpm prisma migrate deploy

# 3. Wait for Railway redeploy (watch dashboard)

# 4. Spot-check 5 routes
curl -s $PROD_URL/api/health | jq .
# (test login, agents list, KB search, chat, heartbeat)

# 5. Flip flag
railway env set RLS_ENFORCEMENT_ENABLED=true
# (triggers Railway redeploy)

# 6. Monitor Sentry for 30 min
# Alert threshold: "permission denied for table X" > 5/min → ROLLBACK
\`\`\`

## Rollback triggers (any one fires → execute rollback)

| Trigger | Action |
|---------|--------|
| 5xx rate > baseline + 1% | Layer 1 |
| p95 latency > baseline + 25% | Layer 1 |
| Sentry: "permission denied" > 5/min | Layer 1 |
| Sentry: "Tenant context not set" > 5/min | Layer 1 |
| User: "can't see my agents" | Layer 1 |
| Admin panel returns 403 | Layer 2 |
| Public chat returns empty | Layer 2 (RLS_DISABLED_TABLES=Agent) |
| Single table errors | Layer 2 (add to RLS_DISABLED_TABLES) |

## Rollback procedure

\`\`\`bash
# Layer 1 — disable enforcement (no migration needed, 60s recovery)
railway env set RLS_ENFORCEMENT_ENABLED=false

# Layer 2 — disable specific tables (no deploy needed)
bash skills/rls-rollout/scripts/rollback.sh --disable-tables=Agent,Template

# Layer 3 — revert migration commit
git revert <migration-commit-sha>
DATABASE_URL=$PROD_DATABASE_URL pnpm prisma migrate deploy

# Layer 4 — nuclear SQL (requires DB superuser access)
bash skills/rls-rollout/scripts/rollback.sh --nuclear --confirm=RLS_DISABLE_ALL
\`\`\`

---

## Per-table details
${tables.map((t) => tableSection(t, phaseNum)).join("")}

---

## Post-cutover monitoring (48h)

- [ ] Sentry: no new "permission denied" errors
- [ ] Railway metrics: p95 latency within 10% of baseline
- [ ] BullMQ dashboard: no unexpected job failures
- [ ] Spot-test cross-tenant access (verify orgA cannot see orgB data)
`;

  writeFileSync(outFile, content);
  console.log(`✓ Runbook: ${outFile.replace(ROOT + "/", "")}`);
  console.log(`  Tables covered: ${tables.map((t) => t.name).join(", ")}`);
}

run();
