#!/usr/bin/env tsx
/**
 * step4-isolation-tests.ts — Generate cross-tenant isolation test stubs.
 *
 * For each table in a given phase, generates a Vitest test stub covering:
 *   - orgA cannot SELECT orgB's rows
 *   - orgA cannot UPDATE orgB's rows
 *   - orgA cannot DELETE orgB's rows
 *   - orgA INSERT is rejected when organizationId mismatch
 *
 * Output files are placed in skills/rls-rollout/tests/generated/.
 * Tests are marked .skip by default — unskip after applying migrations to staging.
 *
 * Usage:
 *   pnpm tsx skills/rls-rollout/scripts/step4-isolation-tests.ts --phase=1
 *   pnpm tsx skills/rls-rollout/scripts/step4-isolation-tests.ts --table=Agent
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../tests/generated");

interface TableSpec {
  name: string;
  tenantCol: "organizationId" | "userId";
  phase: number;
}

const PHASE_1_TABLES: TableSpec[] = [
  { name: "Agent", tenantCol: "organizationId", phase: 1 },
  { name: "AgentPermissionGrant", tenantCol: "organizationId", phase: 1 },
  { name: "ApprovalPolicy", tenantCol: "organizationId", phase: 1 },
  { name: "CompanyMission", tenantCol: "organizationId", phase: 1 },
  { name: "Department", tenantCol: "organizationId", phase: 1 },
  { name: "Goal", tenantCol: "organizationId", phase: 1 },
  { name: "HeartbeatConfig", tenantCol: "organizationId", phase: 1 },
  { name: "HeartbeatContext", tenantCol: "organizationId", phase: 1 },
  { name: "HeartbeatRun", tenantCol: "organizationId", phase: 1 },
  { name: "Invitation", tenantCol: "organizationId", phase: 1 },
  { name: "OrganizationMember", tenantCol: "organizationId", phase: 1 },
  { name: "PolicyDecision", tenantCol: "organizationId", phase: 1 },
  { name: "Template", tenantCol: "organizationId", phase: 1 },
];

function generateTestFile(table: TableSpec): string {
  const modelVar = table.name.charAt(0).toLowerCase() + table.name.slice(1);

  return `import { describe, it, beforeAll, afterAll, expect } from "vitest";
import { getRLSClient } from "../_helpers/get-rls-client";
import type { PrismaClient } from "@/generated/prisma";

/**
 * Phase ${table.phase} — ${table.name} cross-tenant isolation tests.
 * Generated by step4-isolation-tests.ts. Unskip after RLS migration applied to staging.
 */
describe.skip("RLS Phase ${table.phase}: ${table.name} isolation", () => {
  let orgAId: string;
  let orgBId: string;
  let ${modelVar}AId: string;
  let ${modelVar}BId: string;
  let prismaA: PrismaClient;
  let prismaB: PrismaClient;
  let cleanups: Array<() => Promise<void>> = [];

  beforeAll(async () => {
    const admin = await getRLSClient("setup", "system", true);
    cleanups.push(admin.cleanup);

    // Create two isolated orgs
    const orgA = await admin.prisma.organization.create({
      data: { name: "TestOrgA_${table.name}", slug: "test-orga-${modelVar}" },
    });
    const orgB = await admin.prisma.organization.create({
      data: { name: "TestOrgB_${table.name}", slug: "test-orgb-${modelVar}" },
    });
    orgAId = orgA.id;
    orgBId = orgB.id;

    // TODO: Insert test rows for ${table.name} in each org
    // ${modelVar}AId = (await admin.prisma.${modelVar}.create({ data: { ...minimal, ${table.tenantCol}: orgAId } })).id;
    // ${modelVar}BId = (await admin.prisma.${modelVar}.create({ data: { ...minimal, ${table.tenantCol}: orgBId } })).id;

    const clientA = await getRLSClient(orgAId, "userA_${modelVar}");
    const clientB = await getRLSClient(orgBId, "userB_${modelVar}");
    prismaA = clientA.prisma;
    prismaB = clientB.prisma;
    cleanups.push(clientA.cleanup, clientB.cleanup);
  });

  afterAll(async () => {
    for (const fn of cleanups) await fn();
  });

  it("orgA SELECT cannot see orgB rows", async () => {
    // When RLS is enforced, orgA should only see its own ${modelVar}s
    // const rows = await prismaA.${modelVar}.findMany();
    // expect(rows.find((r) => r.id === ${modelVar}BId)).toBeUndefined();
    // expect(rows.find((r) => r.id === ${modelVar}AId)).toBeDefined();
    expect(true).toBe(true); // Replace with real assertion above
  });

  it("orgA cannot UPDATE orgB row", async () => {
    // RLS hides orgB rows, so update returns "Record not found"
    // await expect(
    //   prismaA.${modelVar}.update({ where: { id: ${modelVar}BId }, data: { updatedAt: new Date() } })
    // ).rejects.toThrow();
    expect(true).toBe(true); // Replace with real assertion above
  });

  it("orgA cannot DELETE orgB row", async () => {
    // await expect(
    //   prismaA.${modelVar}.delete({ where: { id: ${modelVar}BId } })
    // ).rejects.toThrow();
    expect(true).toBe(true); // Replace with real assertion above
  });

  it("INSERT with wrong ${table.tenantCol} is rejected", async () => {
    // RLS WITH CHECK should reject inserts with orgB's id from orgA's context
    // await expect(
    //   prismaA.${modelVar}.create({ data: { ...minimal, ${table.tenantCol}: orgBId } })
    // ).rejects.toThrow();
    expect(true).toBe(true); // Replace with real assertion above
  });
});
`;
}

function run(): void {
  const args = process.argv.slice(2);
  const phaseArg = args.find((a) => a.startsWith("--phase="))?.split("=")[1];
  const tableArg = args.find((a) => a.startsWith("--table="))?.split("=")[1];

  let tables: TableSpec[] = [];

  if (phaseArg === "1") {
    tables = PHASE_1_TABLES;
  } else if (tableArg) {
    const found = PHASE_1_TABLES.find((t) => t.name === tableArg);
    if (!found) {
      console.error(`Unknown table: ${tableArg}. Add it to PHASE_1_TABLES or update this script.`);
      process.exit(1);
    }
    tables = [found];
  } else {
    console.error("Usage: --phase=1  OR  --table=<ModelName>");
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });

  for (const table of tables) {
    const outFile = resolve(OUT_DIR, `${table.name.toLowerCase()}.isolation.test.ts`);
    writeFileSync(outFile, generateTestFile(table));
    console.log(`✓ Generated: tests/generated/${table.name.toLowerCase()}.isolation.test.ts`);
  }

  console.log(
    `\n${tables.length} test stubs generated in skills/rls-rollout/tests/generated/`
  );
  console.log("Tests are marked .skip — unskip after applying migrations to staging.");
}

run();
