#!/usr/bin/env tsx
/**
 * step2-classify.ts — Verify model classifications against expected counts.
 *
 * Reads model-classifications.json (generated by step1-inventory.ts) and
 * validates that counts match expected values from the master plan. Reports
 * any model whose classification differs from the manually-verified reference
 * in reference/model-classifications.md.
 *
 * Usage:
 *   pnpm tsx skills/rls-rollout/scripts/step2-classify.ts
 *   pnpm tsx skills/rls-rollout/scripts/step2-classify.ts --update-md
 *
 * Prerequisites:
 *   Run step1-inventory.ts first to generate model-classifications.json
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../..");
const JSON_PATH = resolve(__dirname, "../reference/model-classifications.json");
const MD_PATH = resolve(__dirname, "../reference/model-classifications.md");

type Classification =
  | "TENANT_DIRECT"
  | "TENANT_INDIRECT"
  | "USER_OWNED"
  | "GLOBAL"
  | "AMBIGUOUS";

const EXPECTED_COUNTS: Record<Classification, number> = {
  TENANT_DIRECT: 13,
  TENANT_INDIRECT: 36,
  USER_OWNED: 4,
  GLOBAL: 7,
  AMBIGUOUS: 1,
};

const EXPECTED_TOTAL = Object.values(EXPECTED_COUNTS).reduce((a, b) => a + b, 0);

// Ground-truth classification from schema analysis + master plan
const KNOWN_CLASSIFICATIONS: Record<string, Classification> = {
  // GLOBAL (7)
  User: "GLOBAL",
  VerificationToken: "GLOBAL",
  Skill: "GLOBAL",
  Organization: "GLOBAL",
  PipelineTemplate: "GLOBAL",
  Account: "GLOBAL",
  Session: "GLOBAL",
  // TENANT_DIRECT (13)
  Agent: "TENANT_DIRECT",
  AgentPermissionGrant: "TENANT_DIRECT",
  ApprovalPolicy: "TENANT_DIRECT",
  CompanyMission: "TENANT_DIRECT",
  Department: "TENANT_DIRECT",
  Goal: "TENANT_DIRECT",
  HeartbeatConfig: "TENANT_DIRECT",
  HeartbeatContext: "TENANT_DIRECT",
  HeartbeatRun: "TENANT_DIRECT",
  Invitation: "TENANT_DIRECT",
  OrganizationMember: "TENANT_DIRECT",
  PolicyDecision: "TENANT_DIRECT",
  Template: "TENANT_DIRECT",
  // USER_OWNED (4)
  ApiKey: "USER_OWNED",
  CLIGeneration: "USER_OWNED",
  GoogleOAuthToken: "USER_OWNED",
  MCPServer: "USER_OWNED",
  // AMBIGUOUS (1)
  AuditLog: "AMBIGUOUS",
};

interface ModelEntry {
  name: string;
  classification: Classification;
  tenantPath: string;
  notes: string;
}

interface Inventory {
  totalModels: number;
  counts: Record<Classification, number>;
  models: ModelEntry[];
}

function run(): void {
  if (!existsSync(JSON_PATH)) {
    console.error("ERROR: model-classifications.json not found.");
    console.error("Run step1-inventory.ts first:\n  pnpm tsx skills/rls-rollout/scripts/step1-inventory.ts");
    process.exit(1);
  }

  const inventory: Inventory = JSON.parse(readFileSync(JSON_PATH, "utf-8"));
  let pass = 0;
  let fail = 0;

  console.log("=== STEP 2: Classification Verification ===\n");

  // Total count check
  if (inventory.totalModels === EXPECTED_TOTAL) {
    console.log(`✓ Total models: ${inventory.totalModels}`);
    pass++;
  } else {
    console.log(`✗ Total models: ${inventory.totalModels} (expected ${EXPECTED_TOTAL})`);
    fail++;
  }

  // Per-classification count checks
  console.log("\nClassification counts:");
  for (const [cls, expected] of Object.entries(EXPECTED_COUNTS) as [Classification, number][]) {
    const actual = inventory.counts[cls] ?? 0;
    const icon = actual === expected ? "✓" : "✗";
    console.log(
      `  ${icon} ${cls.padEnd(18)} ${actual} / ${expected} expected`
    );
    if (actual === expected) pass++;
    else fail++;
  }

  // Per-model classification checks
  const mismatches: Array<{ name: string; actual: Classification; expected: Classification }> = [];
  const unknown: string[] = [];

  for (const model of inventory.models) {
    const expected = KNOWN_CLASSIFICATIONS[model.name];
    if (!expected) {
      unknown.push(model.name);
      continue;
    }
    if (model.classification !== expected) {
      mismatches.push({
        name: model.name,
        actual: model.classification,
        expected,
      });
    }
  }

  if (mismatches.length === 0) {
    console.log("\n✓ All known model classifications match reference");
    pass++;
  } else {
    console.log(`\n✗ ${mismatches.length} classification mismatches:`);
    for (const m of mismatches) {
      console.log(`    ${m.name}: got ${m.actual}, expected ${m.expected}`);
    }
    fail++;
  }

  if (unknown.length > 0) {
    console.log(`\n⚠ ${unknown.length} models not in reference (new models?):`);
    for (const name of unknown) console.log(`    ${name}`);
  }

  // Update markdown if requested
  if (process.argv.includes("--update-md")) {
    updateMarkdown(inventory);
    console.log(`\n✓ Updated ${MD_PATH}`);
  }

  console.log(`\n=== Results: ${pass} pass, ${fail} fail ===`);
  process.exit(fail > 0 ? 1 : 0);
}

function updateMarkdown(inventory: Inventory): void {
  const byClass: Record<Classification, ModelEntry[]> = {
    TENANT_DIRECT: [],
    TENANT_INDIRECT: [],
    USER_OWNED: [],
    GLOBAL: [],
    AMBIGUOUS: [],
  };

  for (const m of inventory.models) byClass[m.classification].push(m);

  const lines = [
    "# Model Classifications",
    "",
    `Generated by \`step2-classify.ts\` from \`prisma/schema.prisma\`.`,
    `Last updated: ${new Date().toISOString().slice(0, 10)}`,
    "",
  ];

  for (const [cls, models] of Object.entries(byClass) as [Classification, ModelEntry[]][]) {
    lines.push(`## ${cls} (${models.length})`);
    lines.push("");
    lines.push("| Model | Tenant Path | Notes |");
    lines.push("|-------|-------------|-------|");
    for (const m of models.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`| ${m.name} | ${m.tenantPath} | ${m.notes} |`);
    }
    lines.push("");
  }

  writeFileSync(MD_PATH, lines.join("\n"));
}

run();
