/**
 * SDLC Pipeline Orchestrator — P6
 *
 * Executes a PipelineRun step-by-step, wiring together:
 *   - Codebase RAG        (index /tmp/sdlc → inject relevant code per step)
 *   - Multi-step planning (discovery → architecture → implementation → review)
 *   - Feedback loop       (test failures → retry implementation up to 3×)
 *   - Meta-Orchestrator   (task analysis + pipeline config)
 *   - ECC agent templates (per-step system prompts)
 *   - Vercel AI SDK       (generateText per step)
 *   - P3 Learn Hook       (fire-and-forget after each step)
 *   - BullMQ progress     (job.updateProgress between steps)
 *
 * Phase classification:
 *   PLANNING_STEPS       — discovery, architect, tdd_guide  → produce architecturePlan
 *   IMPLEMENTATION_STEPS — codegen, developer, implementation → produce code; receive architecturePlan + RAG
 *   TEST_STEPS           — sandbox, run_tests, test_runner  → detect failures → trigger feedback loop
 *   REVIEW_STEPS         — code_reviewer, sec_reviewer      → full context
 *
 * Feedback loop:
 *   After a TEST_STEP output indicates failure, the orchestrator re-runs the
 *   most recent IMPLEMENTATION_STEP with the failure report injected.
 *   Max retries: MAX_RETRIES (3). Each retry also re-runs the TEST_STEP to
 *   verify the fix before continuing.
 */

import { rmSync } from "node:fs";
import { logger } from "@/lib/logger";
import { startSpan } from "@/lib/observability/tracer";
import { recordTokenUsage, recordChatLatency } from "@/lib/observability/metrics";
import {
  indexCodebase,
  searchCodebase,
  buildCodeContext,
} from "./codebase-rag";
import {
  runFeedbackIteration,
  didTestsFail,
  MAX_RETRIES,
} from "./feedback-loop";
import {
  executeRealTests,
  executeRealTestsFromFiles,
  runWorkspaceTests,
  type ParsedFile,
} from "./code-extractor";
import { CodeGenOutputSchema } from "./schemas";
import { resolveStepModel, getEscalationModel, resolveStepModelAdaptive } from "./model-router";
import type { StepPhase } from "./model-router";
import type { StepMetric } from "./metrics-collector";
import {
  getCachedImportGraph,
  identifyAffectedFiles,
  buildBlastRadiusContext,
} from "./scope-analyzer";
import { enrichWithSemanticSummaries, buildModuleMapContext } from "./module-map";
import type { ModuleEntry } from "./module-map";
import { parseSearchReplaceBlocks, applyPatchToWorkspace } from "./patch-applier";

/** Base directory for SDLC pipeline workspaces — each run gets its own subdirectory */
const SDLC_WORKSPACE_BASE = "/tmp/sdlc";

/** Steps that produce the architecture/plan document used by later steps.
 *  Includes both bare IDs (used in standalone flows) and ecc-prefixed IDs
 *  (generated by the meta-orchestrator) so phase tracking works regardless
 *  of which pipeline source is used. */
const PLANNING_STEPS = new Set([
  // Bare IDs — standalone flows
  "discovery", "architect", "architecture", "planner",
  "tdd_guide", "security_eng", "project_context",
  // ECC-prefixed IDs — meta-orchestrator pipelines
  "ecc-architect", "ecc-planner", "ecc-tdd-guide",
  "ecc-security-engineer", "ecc-security-reviewer",
]);

/** Steps that produce implementation code — receive architecturePlan + RAG context.
 *  Includes both bare IDs and ecc-prefixed variants. */
const IMPLEMENTATION_STEPS = new Set([
  // Bare IDs
  "codegen", "developer", "implementation", "coder",
  "code_generator", "feature_developer",
  // ECC-prefixed IDs
  "ecc-frontend-developer", "ecc-refactor-cleaner",
  "ecc-build-error-resolver", "ecc-implementer",
]);

/** Steps whose output may indicate test failures — trigger feedback loop.
 *  NOTE: infrastructure nodes (sandbox_verify) are intentionally excluded —
 *  they run inline and return static strings that can never signal failures. */
const TEST_STEPS = new Set([
  // Bare IDs
  "sandbox", "run_tests", "test_runner",
  // ECC-prefixed IDs
  "ecc-e2e-runner", "ecc-tdd-pipeline",
]);

/** Infrastructure nodes that are not real agents — executed inline */
const INFRASTRUCTURE_NODES = new Set(["project_context", "sandbox_verify"]);

/** System prompts for infrastructure nodes */
const INFRA_PROMPTS: Record<string, string> = {
  project_context: "Gathering project context and indexing existing codebase...",
  sandbox_verify: "Verifying sandbox environment...",
};

/** Per-step timeout for AI calls (5 minutes). Prevents hung pipelines. */
const STEP_TIMEOUT_MS = 5 * 60 * 1000;

/** Maximum total context document size in characters. */
const MAX_CONTEXT_CHARS = 24_000;

/**
 * Per-step output slice when adding to the context window.
 * Each step stores up to this many characters in contextParts.
 * 6 000 chars ≈ ~1 500 tokens — enough for a full planning document or
 * a compact implementation summary without dominating the context window.
 */
const CONTEXT_SLICE_PER_STEP = 6_000;

/**
 * Number of most-recent steps whose context is always preserved at full
 * CONTEXT_SLICE_PER_STEP length even when the total exceeds MAX_CONTEXT_CHARS.
 * Protects the implementation and test steps that immediately precede the
 * current step — the output most critical for continuity.
 */
const PROTECTED_RECENT_STEPS = 2;

/** RAG results for planning, test, and review steps — enough context without prompt bloat. */
const RAG_TOP_K_DEFAULT = 5;

/**
 * RAG results for implementation steps — higher limit because the code generator
 * needs more existing patterns, type definitions, and conventions to write
 * correct, consistent code without hallucinating APIs.
 */
const RAG_TOP_K_IMPLEMENTATION = 12;

// ---------------------------------------------------------------------------
// Main entry point — called by the BullMQ worker
// ---------------------------------------------------------------------------

export interface OrchestratorInput {
  runId: string;
  agentId: string;
  userId?: string;
  taskDescription: string;
  pipeline: string[];
  modelId?: string;
  /** Resume from this step index (0-based). Steps before this are skipped.
   *  Existing stepResults for skipped steps are loaded into context. */
  startFromStep?: number;
  /** Pre-loaded step results from a previous (interrupted) run.
   *  Keys are stringified step indices, values are the step outputs. */
  existingStepResults?: Record<string, string>;
  /**
   * Per-step model overrides. Keys are step IDs (e.g. "codegen", "ecc-frontend-developer").
   * When a step ID is found here, its value is used as the modelId for that step's AI call,
   * its learn hook, and any feedback loop iterations triggered by that step.
   * Falls back to the top-level `modelId` (or "gpt-4o-mini") when no override is present.
   */
  stepModelOverrides?: Record<string, string>;
  /**
   * Override the workspace directory used for file writes and RAG indexing.
   * Defaults to SDLC_WORKSPACE_BASE/{runId} — unique per run.
   * Pass explicitly only in tests to prevent cleanup.
   */
  workspaceDir?: string;
  /**
   * When true, pipeline pauses after the last PLANNING_STEP that is
   * immediately followed by an IMPLEMENTATION_STEP.
   * Defaults to false — all existing callers unaffected.
   */
  requireApproval?: boolean;
  /**
   * Human feedback injected into the first IMPLEMENTATION_STEP prompt.
   * Set by the approve route when creating the Phase 2 resume job.
   */
  approvalFeedback?: string;
  /** When true, use the smart model router to select the best available model per phase. */
  useSmartRouting?: boolean;
  repoUrl?: string;
}

export interface OrchestratorResult {
  finalOutput: string;
  stepCount: number;
  totalInputTokens: number;
  totalOutputTokens: number;
  durationMs: number;
  cancelled?: boolean;
  /** True when pipeline paused at approval checkpoint (Phase 1 complete). */
  awaitingApproval?: boolean;
  /** Number of steps completed before pause; used by worker for Phase 2 job. */
  planningStepsCompleted?: number;
  /** Per-step telemetry — keyed by step index */
  stepMetrics?: Record<number, StepMetric>;
  prUrl?: string;
  /** Error message from git/PR integration if it failed (pipeline still COMPLETED). */
  gitError?: string;
}

/**
 * Run a full SDLC pipeline.
 *
 * @param input           - Run configuration
 * @param onStepComplete  - Called after each step with (stepIndex, output)
 * @param isCancelled     - Async predicate checked between steps
 * @param onProgress      - Update BullMQ job progress (0–100)
 */
export async function runPipeline(
  input: OrchestratorInput,
  callbacks: {
    onStepComplete: (stepIndex: number, output: string) => Promise<void>;
    isCancelled: () => Promise<boolean>;
    onProgress: (pct: number) => Promise<void>;
  },
): Promise<OrchestratorResult> {
  const {
    runId, agentId, userId, taskDescription, pipeline, modelId,
    startFromStep = 0,
    existingStepResults,
    stepModelOverrides = {},
    requireApproval = false,
    approvalFeedback,
    useSmartRouting = false,
    repoUrl,
  } = input;
  const { onStepComplete, isCancelled, onProgress } = callbacks;

  const workDir = input.workspaceDir ?? `${SDLC_WORKSPACE_BASE}/${runId}`;
  let gitPrUrl: string | undefined;
  let gitError: string | undefined;
  const cleanupWorkspace = !input.workspaceDir;

  // Tracks whether the pipeline exited cleanly (success or cancellation).
  // Set to true at every non-error return point so the finally block
  // knows whether to clean up or preserve the workspace for debugging.
  let pipelineSucceeded = false;

  // Hoisted before try/finally so the finally block can close the span and
  // set final attributes regardless of which code path exits the function.
  const startedAt = Date.now();
  let totalInputTokens = 0;
  let totalOutputTokens = 0;
  const pipelineSpan = startSpan("sdlc.pipeline.run", {
    kind: "client",
    attributes: {
      "sdlc.run.id": runId,
      "sdlc.agent.id": agentId,
      "sdlc.pipeline.step_count": pipeline.length,
    },
  });

  try {
  const { getModel } = await import("@/lib/ai");
  const { generateText, generateObject } = await import("ai");
  const { fireSdkLearnHook } = await import("@/lib/ecc/sdk-learn-hook");
  const { getAgentSystemPrompt, getImplementationSystemPrompt } = await import("./agent-prompts");
  const { loadRelevantMemory } = await import("./pipeline-memory");
  const { loadVaultContext } = await import("./vault-context");

  // Resolve model lazily — gpt-4o-mini is always available, no extra API key needed.
  const resolvedModelId = modelId ?? "gpt-4o-mini";

  const stepMetricsMap: Record<number, StepMetric> = {};

  // Load memory and vault context in parallel — both are non-blocking
  const [priorMemory, vaultContext] = await Promise.all([
    loadRelevantMemory(agentId),
    loadVaultContext(taskDescription),
  ]);

  // Context document — accumulated from previous step outputs
  const contextParts: string[] = [`# Task\n${taskDescription}`];
  if (vaultContext) {
    contextParts.push(vaultContext);
  }
  if (priorMemory) {
    contextParts.push(priorMemory);
  }
  // Number of leading slots in contextParts before step-0's output:
  //   1 when neither vaultContext nor priorMemory
  //   2 when one of them present
  //   3 when both present
  // Used wherever a specific step index must be targeted by offset.
  const CONTEXT_STEP_OFFSET = (vaultContext ? 1 : 0) + (priorMemory ? 1 : 0) + 1;
  const stepOutputs: string[] = [];

  // ── Phase tracking ──────────────────────────────────────────────────────────
  // Accumulated architecture/design plan from all PLANNING_STEPS.
  // Injected verbatim into every IMPLEMENTATION_STEP prompt.
  let architecturePlan = "";

  // Most recent IMPLEMENTATION_STEP state — required for the feedback loop.
  let lastImplStepIdx = -1;
  let lastImplOutput = "";
  let lastImplSystemPrompt = "";
  let lastImplCodeContext = "";

  /**
   * Real-execution resolution state for the most recent IMPLEMENTATION_STEP.
   *
   * "none"      — real-exec was never run (no TS/test files generated, or step not yet reached)
   * "passing"   — real-exec ran and all checks passed (typecheck + tests green)
   * "exhausted" — real-exec ran but max retries were exhausted without fixing failures
   *
   * Used by TEST_STEPs to avoid retrying code that real-exec already verified as passing
   * (TASK 4: decoupled dual feedback loop). When `implResolution === "passing"`, the
   * TEST_STEP feedback loop is skipped entirely — the implementation is already proven.
   */
  let implResolution: "none" | "passing" | "exhausted" = "none";

  // ── RAG: index the workspace codebase ──────────────────────────────────────
  // Best-effort — if the workspace doesn't exist yet the pipeline still runs;
  // RAG context will simply be empty for this run.
  let codebaseReady = false;
  try {
    const { filesIndexed } = await indexCodebase(workDir, agentId);
    codebaseReady = filesIndexed > 0;
    logger.info("Pipeline: codebase indexed for RAG", { runId, filesIndexed });
  } catch (err) {
    logger.warn("Pipeline: codebase indexing skipped — workspace absent or empty", {
      runId,
      error: err instanceof Error ? err.message : String(err),
    });
  }

  // ── AST: extract API signatures from project source ────────────────────
  let astContext = "";
  let moduleMapEntries: ModuleEntry[] = [];
  try {
    const { extractCodeSignatures, formatSignaturesForPrompt } =
      await import("./ast-analyzer");
    const sigs = await extractCodeSignatures();
    astContext = formatSignaturesForPrompt(sigs);
    if (astContext) {
      logger.info("Pipeline: AST signatures extracted", {
        runId, charCount: astContext.length,
      });
    }
    try {
      moduleMapEntries = await enrichWithSemanticSummaries(sigs);
      logger.info("Pipeline: module map enriched", {
        runId, entryCount: moduleMapEntries.length,
      });
    } catch (enrichErr) {
      logger.warn("Pipeline: module map enrichment failed, continuing without it", {
        runId, error: enrichErr instanceof Error ? enrichErr.message : String(enrichErr),
      });
    }
  } catch (astErr) {
    logger.warn("Pipeline: AST extraction failed, continuing without it", {
      runId, error: astErr instanceof Error ? astErr.message : String(astErr),
    });
  }

  // ── Resume support: pre-seed context from a previous interrupted run ────────
  if (startFromStep > 0 && existingStepResults) {
    for (let i = 0; i < startFromStep && i < pipeline.length; i++) {
      const prevOutput = existingStepResults[String(i)];
      if (prevOutput) {
        contextParts.push(
          `# Step ${i + 1} output (${pipeline[i]})\n${prevOutput.slice(0, CONTEXT_SLICE_PER_STEP)}`,
        );
        stepOutputs.push(prevOutput);

        // Restore phase state so IMPLEMENTATION_STEPS and feedback loop work
        // correctly when resuming mid-pipeline.
        if (PLANNING_STEPS.has(pipeline[i])) {
          architecturePlan += `\n\n## ${pipeline[i]}\n${prevOutput.slice(0, 2000)}`;
        }
        if (IMPLEMENTATION_STEPS.has(pipeline[i])) {
          lastImplStepIdx = i;
          lastImplOutput = prevOutput;
          lastImplSystemPrompt = getImplementationSystemPrompt(pipeline[i]);
          lastImplCodeContext = ""; // RAG context unavailable for resumed steps
        }
      }
    }
    logger.info("Pipeline resuming from step", {
      runId,
      startFromStep,
      preloadedSteps: stepOutputs.length,
    });
  }

  // ── Main step loop ──────────────────────────────────────────────────────────
  for (let stepIdx = startFromStep; stepIdx < pipeline.length; stepIdx++) {
    const stepId = pipeline[stepIdx];

    // Progress: 5% start → 90% max, spread evenly across steps
    const pct = Math.min(5 + Math.floor((stepIdx / pipeline.length) * 85), 90);
    await onProgress(pct);

    // Cancellation check before each step
    if (await isCancelled()) {
      logger.info("Pipeline cancelled before step", { runId, stepIdx, stepId });
      pipelineSucceeded = true;
      return {
        finalOutput: buildSummary(stepOutputs, pipeline),
        stepCount: stepIdx,
        totalInputTokens,
        totalOutputTokens,
        durationMs: Date.now() - startedAt,
        cancelled: true,
        stepMetrics: stepMetricsMap,
        prUrl: undefined,
      };
    }

    logger.info("Pipeline step starting", { runId, stepIdx, stepId });

    let stepOutput: string;
    let stepInputTokens = 0;
    let stepOutputTokens = 0;
    const stepStart = Date.now();

    if (INFRASTRUCTURE_NODES.has(stepId)) {
      // ── Infrastructure node: no AI call ──────────────────────────────────
      stepOutput = INFRA_PROMPTS[stepId] ?? `Infrastructure step: ${stepId}`;

    } else {
      // ── Agent step ────────────────────────────────────────────────────────
      const phase: StepPhase = PLANNING_STEPS.has(stepId) ? "planning"
        : IMPLEMENTATION_STEPS.has(stepId) ? "implementation"
        : TEST_STEPS.has(stepId) ? "testing"
        : "other";
      const stepModelId = useSmartRouting
        ? await resolveStepModelAdaptive(phase, stepModelOverrides, stepId, resolvedModelId)
        : resolveStepModel(phase, stepModelOverrides, stepId, resolvedModelId, false);
      const model = getModel(stepModelId);

      const stepSpan = startSpan("sdlc.pipeline.step", {
        kind: "client",
        parentContext: pipelineSpan.traceContext,
        attributes: {
          "sdlc.step.id": stepId,
          "sdlc.step.index": stepIdx,
          "sdlc.step.phase": phase,
          "gen_ai.request.model": stepModelId,
        },
      });

      logger.info("Pipeline: model resolved for step", {
        runId, stepIdx, stepId,
        stepModelId,
        phase,
        isOverride: !!stepModelOverrides[stepId],
        isSmartRouted: useSmartRouting && !stepModelOverrides[stepId],
      });
      // Implementation steps get the extended prompt with mandatory vitest import rules.
      const systemPrompt = IMPLEMENTATION_STEPS.has(stepId)
        ? getImplementationSystemPrompt(stepId)
        : getAgentSystemPrompt(stepId);
      let stepFeedbackAttempts = 0;
      let stepOutcome: "success" | "retried" = "success";

      // RAG: retrieve code relevant to this step
      let codeContext = "";
      if (codebaseReady) {
        try {
          // Use step role + task description as the search query for relevance.
          const ragQuery = `${stepId} ${taskDescription.slice(0, 200)}`;
          const ragTopK = IMPLEMENTATION_STEPS.has(stepId)
            ? RAG_TOP_K_IMPLEMENTATION
            : RAG_TOP_K_DEFAULT;
          const ragResults = await searchCodebase(ragQuery, agentId, ragTopK);
          codeContext = buildCodeContext(ragResults);
          logger.info("Pipeline: RAG search complete", {
            runId, stepIdx, stepId,
            ragTopK,
            resultsReturned: ragResults.length,
          });
        } catch (err) {
          logger.warn("Pipeline: RAG search failed for step", {
            runId, stepIdx, stepId,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }

      // ── Blast radius: import-graph context for implementation steps ─────────
      let blastRadiusContext = "";
      if (IMPLEMENTATION_STEPS.has(stepId)) {
        try {
          const graph = await getCachedImportGraph(agentId);
          const affected = identifyAffectedFiles(taskDescription, graph);
          blastRadiusContext = await buildBlastRadiusContext(affected);
        } catch {
          // best-effort — never block step execution
        }
      }

      // Prompt assembly — layered by phase
      const contextDoc = buildContextDoc(contextParts, CONTEXT_STEP_OFFSET);
      const promptSections: string[] = [contextDoc];

      // IMPLEMENTATION_STEPS receive the full architecture plan so the AI
      // knows exactly what to build before writing a single line of code.
      if (IMPLEMENTATION_STEPS.has(stepId) && architecturePlan) {
        promptSections.push(
          `\n\n---\n\n# Architecture & Design Plan\n${architecturePlan.slice(0, 3000)}`,
        );
      }

      // All steps get RAG-injected code context when available.
      if (codeContext) {
        promptSections.push(`\n\n---\n\n${codeContext}`);
      }

      const astSection = IMPLEMENTATION_STEPS.has(stepId) && astContext
        ? `\n\n${astContext}`
        : "";

      const moduleMapSection = PLANNING_STEPS.has(stepId) && moduleMapEntries.length > 0
        ? `\n\n${buildModuleMapContext(moduleMapEntries, taskDescription)}`
        : "";

      // Prepend human feedback to the FIRST implementation step only
      const alreadyHasImpl = stepOutputs
        .slice(0, stepIdx)
        .some((_, i) => IMPLEMENTATION_STEPS.has(pipeline[i]));
      const approvalPrefix =
        approvalFeedback &&
        IMPLEMENTATION_STEPS.has(stepId) &&
        !alreadyHasImpl
          ? `## Human Feedback on Architecture Plan\n${approvalFeedback}\n\n`
          : "";

      promptSections.push(
        `\n\n---\n\n# Instructions for this step (${stepId})`,
        `Apply your expertise to the task above. Be specific, actionable, and thorough.`,
        `Reference and build upon any previous step outputs shown in the context above.`,
      );

      const prompt = approvalPrefix + promptSections.join("\n") + astSection
        + (blastRadiusContext ? `\n\n${blastRadiusContext}` : "")
        + moduleMapSection;

      // ── AI call — structured output for implementation steps, text for all others ─
      // IMPLEMENTATION_STEPS use generateObject() + CodeGenOutputSchema for guaranteed
      // structured file output. All other steps use generateText(). If generateObject()
      // fails (model capability gap), we fall back to generateText() + parseCodeBlocks.
      const ac = new AbortController();
      const timeoutId = setTimeout(() => ac.abort(), STEP_TIMEOUT_MS);

      // Holds structured ParsedFile[] when generateObject succeeds — passed directly to
      // executeRealTestsFromFiles to avoid round-tripping through markdown.
      let implFiles: ParsedFile[] | null = null;

      try {
        if (IMPLEMENTATION_STEPS.has(stepId)) {
          // ── Structured output path (2026 standard) ──────────────────────────
          try {
            const result = await generateObject({
              model,
              system: systemPrompt,
              prompt,
              schema: CodeGenOutputSchema,
              maxOutputTokens: 8192, // Larger budget — full file content in response
              abortSignal: ac.signal,
              // Disable OpenAI strict-mode response_format — our Zod schema uses optional()
              // fields and min/max constraints that are rejected by strict mode. Using
              // strictJsonSchema: false falls back to JSON mode with client-side Zod validation.
              providerOptions: {
                openai: { strictJsonSchema: false },
              },
            });

            stepInputTokens = result.usage.inputTokens ?? 0;
            stepOutputTokens = result.usage.outputTokens ?? 0;

            // Runtime guard: schema no longer uses .min(1) (OpenAI strict-mode
            // rejects the minItems keyword), so we check here instead.
            if (result.object.files.length === 0) {
              throw new Error(
                "generateObject returned empty files array — falling back to generateText",
              );
            }

            // Convert structured files to ParsedFile[] for writeToWorkspace
            implFiles = result.object.files.map((f) => ({
              path: f.path,
              content: f.content,
              language: f.language,
            }));

            // Build readable markdown for context accumulation and the feedback loop.
            // Subsequent steps (reviewers, test runners) must be able to read
            // what the implementation step produced.
            stepOutput = serializeCodeGenOutput(result.object);

            logger.info("Pipeline: generateObject succeeded for implementation step", {
              runId, stepIdx, stepId,
              filesCount: implFiles.length,
              summary: result.object.summary.slice(0, 100),
            });
          } catch (structuredErr) {
            // generateObject failed — fall back to generateText + parseCodeBlocks.
            // Common causes: model doesn't support structured output, schema too complex.
            const errMsg = structuredErr instanceof Error ? structuredErr.message : String(structuredErr);
            if (structuredErr instanceof Error && structuredErr.name === "AbortError") {
              throw structuredErr; // Let the outer catch handle AbortError
            }
            logger.warn("Pipeline: generateObject failed, falling back to generateText", {
              runId, stepIdx, stepId, error: errMsg,
            });

            const fallback = await generateText({
              model,
              system: systemPrompt,
              prompt,
              maxOutputTokens: 4096,
              abortSignal: ac.signal,
            });

            stepOutput = fallback.text;
            stepInputTokens = fallback.usage.inputTokens ?? 0;
            stepOutputTokens = fallback.usage.outputTokens ?? 0;
            implFiles = null; // signals executeRealTests (markdown parsing path)
          }
        } else {
          // ── Text generation path — planning, review, test steps ─────────────
          const result = await generateText({
            model,
            system: systemPrompt,
            prompt,
            maxOutputTokens: 4096,
            abortSignal: ac.signal,
          });

          stepOutput = result.text;
          stepInputTokens = result.usage.inputTokens ?? 0;
          stepOutputTokens = result.usage.outputTokens ?? 0;
        }
      } catch (err) {
        if (err instanceof Error && err.name === "AbortError") {
          throw new Error(
            `Pipeline step ${stepIdx} (${stepId}) timed out after ${STEP_TIMEOUT_MS / 1000}s`,
          );
        }
        throw err;
      } finally {
        clearTimeout(timeoutId);
      }

      totalInputTokens += stepInputTokens;
      totalOutputTokens += stepOutputTokens;

      const stepDurationMs = Date.now() - stepStart;

      // Emit per-step OTEL metrics — non-blocking
      recordTokenUsage(agentId, stepModelId, stepInputTokens, stepOutputTokens);
      recordChatLatency(agentId, stepModelId, stepDurationMs);

      // Fire learn hook — non-blocking, never throws
      void fireSdkLearnHook({
        agentId,
        userId,
        task: `[${stepId}] ${taskDescription.slice(0, 500)}`,
        response: stepOutput.slice(0, 2000),
        modelId: stepModelId,
        durationMs: stepDurationMs,
        inputTokens: stepInputTokens,
        outputTokens: stepOutputTokens,
      });

      // ── Phase tracking ────────────────────────────────────────────────────
      if (PLANNING_STEPS.has(stepId)) {
        // Accumulate each planning step's output into a single architecture plan.
        // Each section is labelled so the implementation agent knows which
        // part of the plan came from which specialist.
        architecturePlan += `\n\n## ${stepId}\n${stepOutput.slice(0, 2000)}`;
        logger.info("Pipeline: planning step done — architecture plan updated", {
          runId, stepIdx, stepId, planLength: architecturePlan.length,
        });
      }

      if (IMPLEMENTATION_STEPS.has(stepId)) {
        // Snapshot this step so the feedback loop can re-run it with failure context.
        lastImplStepIdx = stepIdx;
        lastImplOutput = stepOutput;
        lastImplSystemPrompt = systemPrompt;
        lastImplCodeContext = codeContext;
        // Reset resolution — this is a new implementation attempt; the previous
        // step's real-exec outcome is irrelevant for the upcoming TEST_STEP check.
        implResolution = "none";

        // ── Real execution: parse code blocks → write files → compile + test ─
        // This is the core upgrade: instead of relying on an AI to "simulate"
        // test results, we write the actual generated code to disk, run the
        // TypeScript compiler, and run Vitest. The real stdout/stderr is then
        // fed into the feedback loop so the AI fixes actual errors.
        // Tracks whether the implementation step produced zero files after real execution.
        // Declared outside the try/catch so we can throw after the best-effort block,
        // since errors thrown inside the catch are swallowed as "best-effort".
        let zeroFilesAfterExec = false;

        try {
          // Use structured ParsedFile[] when generateObject succeeded (avoids markdown round-trip);
          // fall back to parseCodeBlocks on the text output when generateText was used.
          const execResult = implFiles
            ? await executeRealTestsFromFiles(implFiles, workDir, agentId)
            : await executeRealTests(stepOutput, workDir, agentId);

          if (execResult.filesWritten === 0) {
            logger.error("Pipeline: implementation step produced zero files", {
              runId, stepIdx, stepId,
              usedStructuredOutput: implFiles !== null,
              implFilesCount: implFiles?.length ?? 0,
              testOutput: execResult.testOutput.slice(0, 200),
              stepOutputLength: stepOutput.length,
              stepOutputSample: stepOutput.slice(0, 300),
            });
            zeroFilesAfterExec = true;
          }

          if (execResult.filesWritten > 0) {
            // Gate the feedback loop on test failures only.
            // Typecheck failures are intentionally excluded: the sdlc-generated tsconfig
            // may not resolve all @/* path aliases in every environment (Railway worker
            // vs local dev), producing false "Cannot find module" TS errors for code that
            // is actually correct. Tests (vitest) are the authoritative correctness signal.
            const realFailed = !execResult.testsPassed;

            logger.info("Pipeline: real execution after implementation step", {
              runId, stepIdx, stepId,
              filesWritten: execResult.filesWritten,
              typecheckPassed: execResult.typecheckPassed,
              testsPassed: execResult.testsPassed,
              feedbackLoopGate: realFailed ? "FAILED (tests)" : "PASSED",
            });

            if (realFailed) {
              // ── Feedback loop on real failures ──────────────────────────────
              logger.info("Pipeline: real compile/test failures — entering feedback loop", {
                runId, stepIdx, stepId, maxRetries: MAX_RETRIES,
              });

              let currentImpl = stepOutput;
              let currentTestOutput = execResult.testOutput;

              for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
                stepFeedbackAttempts++;
                const escalatedModelId = getEscalationModel(phase, stepModelId, attempt);
                const feedbackResult = await runFeedbackIteration(
                  {
                    taskDescription,
                    architecturePlan,
                    previousImplementation: currentImpl,
                    testOutput: currentTestOutput,
                    codebaseContext: codeContext,
                    agentId,
                    modelId: escalatedModelId,
                    attempt,
                  },
                  systemPrompt,
                );

                // Aggregate feedback-loop token usage into pipeline totals
                totalInputTokens += feedbackResult.inputTokens;
                totalOutputTokens += feedbackResult.outputTokens;

                if (!feedbackResult.success) {
                  logger.warn("Pipeline: real-exec feedback iteration failed", { runId, attempt });
                  break;
                }

                currentImpl = feedbackResult.revisedImplementation;

                // ── SEARCH/REPLACE patch application for attempt >= 2 ────────────
                if (attempt >= 2) {
                  const blocks = parseSearchReplaceBlocks(currentImpl);
                  if (blocks.length > 0) {
                    const patchResult = await applyPatchToWorkspace(blocks, workDir, undefined);
                    if (patchResult.applied > 0) {
                      logger.info("Pipeline: SEARCH/REPLACE patches applied", {
                        runId, attempt, applied: patchResult.applied, failed: patchResult.failed,
                      });
                      const patchTestResult = await runWorkspaceTests(workDir, agentId);
                      if (patchTestResult.typecheckPassed && patchTestResult.testsPassed) {
                        stepOutput = currentImpl + `\n\n---\n\n## Verified by SEARCH/REPLACE patch (attempt ${attempt})\n${patchTestResult.testOutput}`;
                        lastImplOutput = currentImpl;
                        implResolution = "passing";
                        logger.info("Pipeline: SEARCH/REPLACE patch fixed tests", { runId, attempt });
                        break;
                      }
                      currentTestOutput = patchTestResult.testOutput;
                      await onStepComplete(stepIdx, currentImpl);
                      continue;
                    }
                  }
                }

                // Re-run real tests against the revised implementation
                const reExec = await executeRealTests(currentImpl, workDir, agentId);
                currentTestOutput = reExec.testOutput;

                const nowPassing = reExec.typecheckPassed && reExec.testsPassed;
                logger.info("Pipeline: real-exec feedback attempt complete", {
                  runId, attempt, nowPassing,
                });

                // Notify the BullMQ worker of the revised implementation so progress is visible
                await onStepComplete(stepIdx, currentImpl);

                if (nowPassing) {
                  // Update step output to the working implementation
                  stepOutput = currentImpl + `\n\n---\n\n## Verified by real execution (attempt ${attempt})\n${currentTestOutput}`;
                  lastImplOutput = currentImpl;
                  implResolution = "passing"; // Signal TEST_STEP to skip its retry loop
                  logger.info("Pipeline: real execution passing after feedback loop", { runId, attempt });
                  break;
                }

                if (attempt === MAX_RETRIES) {
                  // Append the failure report to the step output for human review
                  stepOutput = currentImpl + `\n\n---\n\n## Real Execution (${MAX_RETRIES} attempts, still failing)\n${currentTestOutput}`;
                  lastImplOutput = currentImpl;
                  implResolution = "exhausted"; // All real-exec retries spent — TEST_STEP may try again
                  stepOutcome = "retried";
                  logger.warn("Pipeline: real-exec max retries reached", { runId, maxRetries: MAX_RETRIES });
                }
              }
            } else {
              // Tests pass — annotate the step output with the verification proof
              stepOutput = stepOutput + `\n\n---\n\n## Real Execution — PASSED\n${execResult.testOutput}`;
              implResolution = "passing"; // Signal TEST_STEP to skip its retry loop
              logger.info("Pipeline: real execution passed on first try", { runId, stepIdx });
            }
          }
        } catch (execErr) {
          // Real execution is best-effort — never block the pipeline
          logger.warn("Pipeline: real execution failed unexpectedly, continuing", {
            runId, stepIdx,
            error: execErr instanceof Error ? execErr.message : String(execErr),
          });
        }

        // Zero-files guard: throw AFTER the best-effort try/catch so the error
        // propagates to the main pipeline handler instead of being swallowed.
        // A pipeline that produces no files is broken — fail fast and clearly.
        if (zeroFilesAfterExec) {
          throw new Error(
            `Implementation step "${stepId}" produced no files. ` +
            `The AI did not generate any code — check model availability, ` +
            `prompt configuration, and structured output support for the selected model.`,
          );
        }
      }

      // Post-loop safety net: if the IMPL_STEP real-exec loop exited via a
      // SEARCH/REPLACE `continue` on the MAX_RETRIES iteration, the
      // `attempt === MAX_RETRIES` block was skipped and stepOutcome was never
      // set to "retried". Correct it here before recording telemetry.
      if (stepFeedbackAttempts > 0 && implResolution !== "passing" && stepOutcome === "success") {
        stepOutcome = "retried";
      }

      // ── Feedback loop — triggered by TEST_STEPS ───────────────────────────
      // Skip the TEST_STEP retry loop when real-exec already verified the
      // implementation as passing. Running it again would be wasteful (6 total
      // retries for the same code) and incorrect (real compiler output already
      // confirmed correctness — an AI test simulation can't add information).
      if (
        TEST_STEPS.has(stepId) &&
        didTestsFail(stepOutput) &&
        lastImplStepIdx >= 0 &&
        implResolution !== "passing"
      ) {
        logger.info("Pipeline: test failures detected — entering feedback loop", {
          runId, stepIdx, stepId, maxRetries: MAX_RETRIES, implResolution,
        });

        let currentImpl = lastImplOutput;
        let currentTestOutput = stepOutput;

        for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
          // ── Step A: AI produces a revised implementation ──────────────────
          stepFeedbackAttempts++;
          const escalatedModelId = getEscalationModel(phase, stepModelId, attempt);
          const feedbackResult = await runFeedbackIteration(
            {
              taskDescription,
              architecturePlan,
              previousImplementation: currentImpl,
              testOutput: currentTestOutput,
              codebaseContext: lastImplCodeContext,
              agentId,
              modelId: escalatedModelId,
              attempt,
            },
            lastImplSystemPrompt,
          );

          // Aggregate feedback-loop token usage into pipeline totals
          totalInputTokens += feedbackResult.inputTokens;
          totalOutputTokens += feedbackResult.outputTokens;

          if (!feedbackResult.success) {
            logger.warn("Pipeline: feedback iteration failed — stopping retry", {
              runId, attempt,
            });
            break;
          }

          currentImpl = feedbackResult.revisedImplementation;

          // Persist the revised implementation so the caller can show progress.
          stepOutputs[lastImplStepIdx] = currentImpl;
          lastImplOutput = currentImpl; // Keep in sync — subsequent TEST_STEPS must see the latest version
          await onStepComplete(lastImplStepIdx, currentImpl);

          // Update the context window so the re-run test step sees the fix.
          // contextParts layout: [task, (priorMemory?), step-0, step-1, …]
          // CONTEXT_STEP_OFFSET accounts for the optional priorMemory slot (1 or 2).
          contextParts[lastImplStepIdx + CONTEXT_STEP_OFFSET] =
            `# Step ${lastImplStepIdx + 1} output (${pipeline[lastImplStepIdx]}) [revised-attempt-${attempt}]\n` +
            currentImpl.slice(0, CONTEXT_SLICE_PER_STEP);

          // ── Step B: Re-run the test step against the revised implementation ─
          const testSystemPrompt = getAgentSystemPrompt(stepId);
          const rerunContextDoc = buildContextDoc(contextParts, CONTEXT_STEP_OFFSET);

          const rerunPrompt = [
            rerunContextDoc,
            `\n\n---\n\n# Revised Implementation (Feedback Attempt ${attempt})`,
            `The implementation has been revised based on the previous test failures.`,
            `Re-run the full test suite against the revised code below:\n`,
            `\`\`\`\n${currentImpl.slice(0, 4_000)}\n\`\`\``,
            `\n\n---\n\n# Instructions for this step (${stepId})`,
            `Run ALL tests again. Report pass/fail for every test case.`,
            `Be precise — if any test still fails, say so explicitly with the failure message.`,
          ].join("\n");

          const testModel = getModel(stepModelId);
          const testAC = new AbortController();
          const testTimeoutId = setTimeout(() => testAC.abort(), STEP_TIMEOUT_MS);

          try {
            const testResult = await generateText({
              model: testModel,
              system: testSystemPrompt,
              prompt: rerunPrompt,
              maxOutputTokens: 4096,
              abortSignal: testAC.signal,
            });

            currentTestOutput = testResult.text;
            totalInputTokens += testResult.usage.inputTokens ?? 0;
            totalOutputTokens += testResult.usage.outputTokens ?? 0;
          } catch (retestErr) {
            logger.warn("Pipeline: test re-run failed in feedback loop", {
              runId, attempt,
              error: retestErr instanceof Error ? retestErr.message : String(retestErr),
            });
            break;
          } finally {
            clearTimeout(testTimeoutId);
          }

          const nowPassing = !didTestsFail(currentTestOutput);
          logger.info("Pipeline: feedback attempt complete", {
            runId, attempt, nowPassing,
          });

          // Tests are green — replace the test step output and stop retrying.
          if (nowPassing) {
            stepOutput = currentTestOutput;
            logger.info("Pipeline: all tests passing after feedback loop", {
              runId, attempt,
            });
            break;
          }

          // Exhausted retries — continue with the best test output we have.
          if (attempt === MAX_RETRIES) {
            stepOutput = currentTestOutput;
            stepOutcome = "retried";
            logger.warn("Pipeline: max retries reached — proceeding with last test output", {
              runId, maxRetries: MAX_RETRIES,
            });
          }
        }
      }

      // Record per-step telemetry
      stepMetricsMap[stepIdx] = {
        stepId,
        phase,
        modelId: stepModelId,
        inputTokens: stepInputTokens,
        outputTokens: stepOutputTokens,
        durationMs: Date.now() - stepStart,
        feedbackAttempts: stepFeedbackAttempts,
        outcome: stepOutcome,
      };

      // Close the step span with final attributes
      stepSpan.setAttributes({
        "gen_ai.usage.input_tokens": stepInputTokens,
        "gen_ai.usage.output_tokens": stepOutputTokens,
        "sdlc.step.duration_ms": Date.now() - stepStart,
        "sdlc.step.outcome": stepOutcome,
        "sdlc.step.feedback_attempts": stepFeedbackAttempts,
      });
      stepSpan.end();
    }

    // ── HITL approval checkpoint ──────────────────────────────────────────
    if (
      requireApproval === true &&
      PLANNING_STEPS.has(stepId) &&
      stepIdx + 1 < pipeline.length &&
      IMPLEMENTATION_STEPS.has(pipeline[stepIdx + 1])
    ) {
      contextParts.push(
        `# Step ${stepIdx + 1} output (${stepId})\n${stepOutput.slice(0, CONTEXT_SLICE_PER_STEP)}`,
      );
      stepOutputs.push(stepOutput);
      await onStepComplete(stepIdx, stepOutput);
      await onProgress(
        Math.min(5 + Math.floor(((stepIdx + 1) / pipeline.length) * 85), 90),
      );
      logger.info("Pipeline: approval checkpoint — pausing for human review", {
        runId, stepIdx, stepId, nextStep: pipeline[stepIdx + 1],
      });
      pipelineSucceeded = true;
      return {
        finalOutput: buildSummary(stepOutputs, pipeline),
        stepCount: stepIdx + 1,
        totalInputTokens,
        totalOutputTokens,
        durationMs: Date.now() - startedAt,
        awaitingApproval: true,
        planningStepsCompleted: stepIdx + 1,
        stepMetrics: stepMetricsMap,
        prUrl: undefined,
      };
    }

    // ── Accumulate context for subsequent steps ─────────────────────────────
    contextParts.push(
      `# Step ${stepIdx + 1} output (${stepId})\n${stepOutput.slice(0, CONTEXT_SLICE_PER_STEP)}`,
    );
    stepOutputs.push(stepOutput);

    // Persist the step result
    await onStepComplete(stepIdx, stepOutput);

    logger.info("Pipeline step completed", {
      runId,
      stepIdx,
      stepId,
      outputLength: stepOutput.length,
    });
  }

  // All steps done
  await onProgress(100);

  // Tier 5 — Git/PR integration (best-effort, never blocks COMPLETED)
  if (repoUrl) {
    const { integrateWithGit } = await import("./git-integration");
    const gitResult = await integrateWithGit({
      repoUrl,
      workDir,
      runId,
      taskDescription: input.taskDescription,
    });
    if (gitResult.success && gitResult.prUrl) {
      gitPrUrl = gitResult.prUrl;
      logger.info("orchestrator: git PR created", { runId, prUrl: gitPrUrl });
    } else {
      gitError = gitResult.error;
      logger.warn("orchestrator: git integration skipped or failed", {
        runId,
        error: gitError,
      });
    }
  }

  const finalOutput = buildSummary(stepOutputs, pipeline);

  pipelineSucceeded = true;
  return {
    finalOutput,
    stepCount: pipeline.length,
    totalInputTokens,
    totalOutputTokens,
    durationMs: Date.now() - startedAt,
    stepMetrics: stepMetricsMap,
    prUrl: gitPrUrl,
    gitError,
  };
  } finally {
    // Close the pipeline span — always fires regardless of success/failure
    pipelineSpan.setAttributes({
      "sdlc.pipeline.total_input_tokens": totalInputTokens,
      "sdlc.pipeline.total_output_tokens": totalOutputTokens,
      "sdlc.pipeline.duration_ms": Date.now() - startedAt,
      "sdlc.pipeline.succeeded": pipelineSucceeded,
    });
    pipelineSpan.end();

    if (cleanupWorkspace) {
      if (pipelineSucceeded) {
        try {
          rmSync(workDir, { recursive: true, force: true });
          logger.info("Pipeline: workspace cleaned up", { runId, workDir });
        } catch (cleanErr) {
          logger.warn("Pipeline: workspace cleanup failed", {
            runId,
            workDir,
            error: cleanErr instanceof Error ? cleanErr.message : String(cleanErr),
          });
        }
      } else {
        logger.error("Pipeline: workspace preserved for post-mortem inspection after failure", {
          runId,
          workDir,
        });
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a structured CodeGenOutput into human-readable markdown.
 *
 * Used in two places:
 *   1. As `stepOutput` for context accumulation — planning/review agents read this.
 *   2. As `lastImplOutput` fed into the feedback loop — the feedback agent reads it.
 *
 * We keep the format close to what `parseCodeBlocks` would produce from free-form
 * AI text so that any code downstream that reads these outputs stays consistent.
 */
function serializeCodeGenOutput(output: import("./schemas").CodeGenOutput): string {
  const sections: string[] = [`## Summary\n\n${output.summary}`];

  for (const file of output.files) {
    const verb = file.isNew ? "New" : "Modified";
    sections.push(
      `### ${verb}: \`${file.path}\`\n\`\`\`${file.language}\n${file.content}\n\`\`\``,
    );
  }

  const deps = output.dependencies ?? [];
  if (deps.length > 0) {
    const depList = deps
      .map((d) => `- \`${d.name}@${d.version}\`${d.isDev ? " (dev)" : ""}`)
      .join("\n");
    sections.push(`### Dependencies\n\n${depList}`);
  }

  const envVars = output.envVariables ?? [];
  if (envVars.length > 0) {
    const envList = envVars
      .map((e) => `- \`${e.key}\` — ${e.description}${e.required ? " *(required)*" : ""}`)
      .join("\n");
    sections.push(`### Environment Variables\n\n${envList}`);
  }

  if (output.prismaSchemaChanges) {
    sections.push(`### Prisma Schema Changes\n\n\`\`\`prisma\n${output.prismaSchemaChanges}\n\`\`\``);
  }

  return sections.join("\n\n");
}

/**
 * Build the context document from accumulated parts, respecting MAX_CONTEXT_CHARS.
 *
 * Strategy:
 *   1. Task description (parts[0]) is never trimmed — always included in full.
 *   2. The PROTECTED_RECENT_STEPS most-recent step outputs are guaranteed to be
 *      included at their full stored size (up to CONTEXT_SLICE_PER_STEP chars each).
 *      This ensures the implementation and test steps that immediately precede the
 *      current step are always visible to the AI in full — they carry the most
 *      critical continuity information.
 *   3. Remaining budget is distributed across older steps newest-first, with
 *      aggressive trimming once the budget is exhausted.
 *
 * Exported for unit testing.
 */
/**
 * @param parts       The full contextParts array: [task, (priorMemory?), step-0, step-1, …]
 * @param preambleCount  How many leading slots are "preamble" (never trimmed).
 *                    Pass 1 when no priorMemory, 2 when priorMemory is present.
 *                    Defaults to 1 for backward compatibility.
 */
export function buildContextDoc(parts: string[], preambleCount = 1): string {
  const joined = parts.join("\n\n---\n\n");
  if (joined.length <= MAX_CONTEXT_CHARS) return joined;

  // Preamble = task + optional priorMemory — always kept at full length, never trimmed.
  const preamble = parts.slice(0, preambleCount);
  const stepParts = parts.slice(preambleCount); // actual step outputs only
  const n = stepParts.length;
  const allocated: string[] = new Array<string>(n);

  // ── Phase 1: lock in the most-recent PROTECTED_RECENT_STEPS steps ──────────
  // These are never sacrificed regardless of total context size.
  const protectedCount = Math.min(PROTECTED_RECENT_STEPS, n);
  let protectedCharsUsed = 0;

  for (let i = n - protectedCount; i < n; i++) {
    // Each protected step is already truncated at CONTEXT_SLICE_PER_STEP when
    // it was pushed into contextParts, so we include it verbatim.
    allocated[i] = stepParts[i];
    protectedCharsUsed += stepParts[i].length;
  }

  // ── Phase 2: distribute remaining budget over older steps newest-first ──────
  // Separator overhead: "\n\n---\n\n" = 9 chars; rough estimate with parts count.
  const separatorOverhead = parts.length * 9;
  const preambleLength = preamble.reduce((sum, p) => sum + p.length, 0);
  let remaining =
    MAX_CONTEXT_CHARS - preambleLength - protectedCharsUsed - separatorOverhead;

  for (let i = n - protectedCount - 1; i >= 0; i--) {
    if (remaining <= 0) {
      // Budget exhausted — keep only the header line so the AI knows the step ran
      allocated[i] = stepParts[i].split("\n")[0] + "\n[context trimmed — budget exhausted]";
    } else if (stepParts[i].length <= remaining) {
      allocated[i] = stepParts[i];
      remaining -= stepParts[i].length;
    } else {
      allocated[i] = stepParts[i].slice(0, remaining) + "\n…[trimmed]";
      remaining = 0;
    }
  }

  return [...preamble, ...allocated].join("\n\n---\n\n");
}

function buildSummary(outputs: string[], pipeline: string[]): string {
  if (outputs.length === 0) return "No steps completed.";

  const sections = outputs.map((out, i) => {
    const stepId = pipeline[i] ?? `step-${i}`;
    const snippet = out.length > 1500 ? `${out.slice(0, 1500)}\n…[truncated]` : out;
    return `## Step ${i + 1}: ${stepId}\n\n${snippet}`;
  });

  return `# Pipeline Execution Summary\n\n${sections.join("\n\n---\n\n")}`;
}
