"""
Investment Memo Generator
Compiles all 5 agent analyses into a structured Investment Memorandum (Markdown + HTML).
"""
from __future__ import annotations
import json
import logging
from datetime import datetime
from typing import Any, Optional

logger = logging.getLogger(__name__)

# ── Memo template ─────────────────────────────────────────────────────────────

MEMO_TEMPLATE = """# Investment Memorandum
## {deal_name}
**Prepared:** {date}  |  **Confidential — For Internal Use Only**

---

## Executive Summary

{executive_summary}

**Overall Score:** {overall_score:.0f} / 100
**Recommendation:** {recommendation}

---

## 1. Deal Overview

| Field | Detail |
|-------|--------|
| **Target Company** | {company_name} |
| **Industry** | {industry} |
| **Country** | {country} |
| **Deal Type** | {deal_type} |
| **Enterprise Value** | ${deal_value_usd:,.0f} |
| **Revenue (LTM)** | ${revenue_usd:,.0f} |
| **EBITDA (LTM)** | ${ebitda_usd:,.0f} |
| **EV / EBITDA** | {ev_ebitda:.1f}x |
| **Target IRR** | {irr_target:.0f}% |

---

## 2. Screening Analysis

**Score: {screening_score:.0f}/100** | **Recommendation: {screening_recommendation}**

{screening_summary}

**Market Attractiveness**
- TAM: ${tam_usd:,.0f}
- Growth Rate: {tam_growth:.1f}% CAGR
- Stage: {market_stage}

**Competitive Moat:** {moat_type} — {moat_strength}

**Green Flags:**
{green_flags}

**Red Flags:**
{red_flags}

---

## 3. Financial Analysis

**Score: {financial_score:.0f}/100** | **Valuation Assessment: {valuation_assessment}**

{financial_summary}

### Returns Analysis (Base Case LBO)

| Metric | Value |
|--------|-------|
| Entry EV | ${entry_ev:,.0f} |
| Exit EV (5yr) | ${exit_ev:,.0f} |
| Base IRR | {irr_base:.1f}% |
| Upside IRR | {irr_upside:.1f}% |
| Downside IRR | {irr_downside:.1f}% |
| MOIC | {moic:.1f}x |

**Value Creation Levers:**
{value_creation_levers}

---

## 4. Risk Assessment

**Score: {risk_score:.0f}/100** | **Overall Risk: {risk_rating}**

{risk_summary}

**Recommended Protections:**
{risk_protections}

---

## 5. Competitive Analysis

**Score: {competitive_score:.0f}/100** | **Market Position: {market_position}**

{competitive_summary}

**Competitive Advantages:**
{competitive_advantages}

**M&A Landscape:** {consolidation_trend}
Comparable transactions: {recent_transactions}

---

## 6. Legal & Compliance

**Score: {legal_score:.0f}/100** | **Legal Risk: {legal_risk_rating}**

{legal_summary}

**Deal Structure:** {deal_structure} ({structure_rationale})

**Conditions Precedent:**
{conditions_precedent}

**Estimated Close:** {close_timeline} months

---

## 7. Score Summary

| Agent | Score | Weight | Weighted |
|-------|-------|--------|---------|
| Screening    | {screening_score:.0f}    | 15% | {w_screening:.1f} |
| Financial    | {financial_score:.0f}    | 30% | {w_financial:.1f} |
| Risk         | {risk_score:.0f}         | 25% | {w_risk:.1f} |
| Competitive  | {competitive_score:.0f}  | 20% | {w_competitive:.1f} |
| Legal        | {legal_score:.0f}        | 10% | {w_legal:.1f} |
| **Overall**  | **{overall_score:.0f}**  | 100% | **{overall_score:.1f}** |

---

## 8. Recommendation

> **{recommendation}**

{final_rationale}

---

*This memorandum was generated by the Deal Flow Agent AI system on {date}.*
*All financial projections are estimates and subject to formal diligence validation.*
"""


class MemoGenerator:
    """Compiles AgentResult outputs into a formatted Investment Memo."""

    def generate(
        self,
        deal_data: dict[str, Any],
        agent_results: dict[str, dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Returns: {title, markdown_body, html_body, executive_summary, recommendation, overall_score}
        """
        scores = self._compute_scores(agent_results)
        recommendation = self._determine_recommendation(scores["overall"])
        executive_summary = self._build_executive_summary(deal_data, agent_results, scores, recommendation)
        markdown = self._render_markdown(deal_data, agent_results, scores, recommendation, executive_summary)

        try:
            import markdown as md_lib
            html_body = md_lib.markdown(markdown, extensions=["tables", "toc"])
        except ImportError:
            html_body = f"<pre>{markdown}</pre>"

        return {
            "title": f"Investment Memo — {deal_data.get('company_name', 'Target')} ({datetime.now().strftime('%b %Y')})",
            "markdown_body": markdown,
            "html_body": html_body,
            "executive_summary": executive_summary,
            "recommendation": recommendation,
            "overall_score": scores["overall"],
        }

    # ── Internal ─────────────────────────────────────────────────────────────

    def _compute_scores(self, results: dict[str, dict[str, Any]]) -> dict[str, float]:
        weights = {
            "screening":   0.15,
            "financial":   0.30,
            "risk":        0.25,
            "competitive": 0.20,
            "legal":       0.10,
        }
        scores: dict[str, float] = {}
        overall = 0.0
        for agent, weight in weights.items():
            s = float((results.get(agent) or {}).get("score", 50))
            scores[agent] = s
            overall += s * weight
        scores["overall"] = round(overall, 1)
        return scores

    def _determine_recommendation(self, score: float) -> str:
        if score >= 72:
            return "BUY — Recommend Proceeding to Exclusivity"
        elif score >= 55:
            return "HOLD — Further Diligence Required"
        else:
            return "PASS — Do Not Proceed"

    def _build_executive_summary(
        self,
        deal: dict[str, Any],
        results: dict[str, dict[str, Any]],
        scores: dict[str, float],
        recommendation: str,
    ) -> str:
        screening = results.get("screening", {})
        financial = results.get("financial", {})
        risk      = results.get("risk", {})

        irr_base = (financial.get("lbo_returns") or {}).get("irr_base", "N/A")
        risk_rating = risk.get("overall_risk_rating", "N/A")
        sc_rec = screening.get("recommendation", "N/A")

        return (
            f"{deal.get('company_name', 'The target')} is a {deal.get('industry', '')} company "
            f"headquartered in {deal.get('country', 'N/A')} with LTM revenue of "
            f"${deal.get('revenue_usd', 0):,.0f} and EBITDA of ${deal.get('ebitda_usd', 0):,.0f}. "
            f"The deal is being evaluated as a {deal.get('deal_type', 'acquisition')} at an implied "
            f"enterprise value of ${deal.get('deal_value_usd', 0):,.0f}.\n\n"
            f"Our five-agent AI diligence system scored the deal **{scores['overall']:.0f}/100**. "
            f"Screening recommendation: **{sc_rec}**. Base case LBO IRR: **{irr_base}%**. "
            f"Overall risk rating: **{risk_rating}**.\n\n"
            f"**Conclusion:** {recommendation}."
        )

    def _render_markdown(
        self,
        deal: dict[str, Any],
        results: dict[str, dict[str, Any]],
        scores: dict[str, float],
        recommendation: str,
        executive_summary: str,
    ) -> str:
        sc  = results.get("screening",   {})
        fi  = results.get("financial",   {})
        ri  = results.get("risk",        {})
        co  = results.get("competitive", {})
        le  = results.get("legal",       {})

        # Helpers
        def _bullets(items: list) -> str:
            return "\n".join(f"- {i}" for i in items) if items else "- None identified"

        def _safe(d: dict, *keys, default="N/A"):
            val = d
            for k in keys:
                if not isinstance(val, dict):
                    return default
                val = val.get(k, default)
            return val if val is not None else default

        ev      = deal.get("deal_value_usd", 0) or 0
        ebitda  = deal.get("ebitda_usd",     1) or 1
        revenue = deal.get("revenue_usd",    1) or 1

        lbo  = fi.get("lbo_returns") or {}
        val  = fi.get("valuation")   or {}
        tam  = sc.get("market_attractiveness") or {}
        moat = sc.get("competitive_moat")      or {}
        rr   = ri.get("deal_structure_recommendations") or {}

        final_rationale = (
            f"Based on a composite score of {scores['overall']:.0f}/100 and a base case IRR of "
            f"{_safe(lbo, 'irr_base')}%, the investment committee is advised to {recommendation.split('—')[0].strip()}. "
            f"Key value creation levers include: "
            f"{'; '.join((fi.get('value_creation_levers') or ['operational improvement'])[:2])}."
        )

        return MEMO_TEMPLATE.format(
            deal_name=deal.get("deal_name", f"{deal.get('company_name', 'Target')} Acquisition"),
            date=datetime.now().strftime("%d %B %Y"),
            executive_summary=executive_summary,
            overall_score=scores["overall"],
            recommendation=recommendation,
            company_name=deal.get("company_name", "N/A"),
            industry=deal.get("industry", "N/A"),
            country=deal.get("country", "N/A"),
            deal_type=deal.get("deal_type", "acquisition"),
            deal_value_usd=ev,
            revenue_usd=revenue,
            ebitda_usd=ebitda,
            ev_ebitda=ev / ebitda,
            irr_target=deal.get("irr_target", 20),
            # Screening
            screening_score=scores["screening"],
            screening_recommendation=sc.get("recommendation", "N/A"),
            screening_summary=sc.get("summary", "No screening data."),
            tam_usd=_safe(tam, "tam_estimate_usd", default=0),
            tam_growth=_safe(tam, "growth_rate_pct", default=0),
            market_stage=_safe(tam, "maturity", default="N/A"),
            moat_type=moat.get("moat_type", "N/A"),
            moat_strength=moat.get("strength", "N/A"),
            green_flags=_bullets(sc.get("green_flags", [])),
            red_flags=_bullets(sc.get("red_flags", [])),
            # Financial
            financial_score=scores["financial"],
            valuation_assessment=_safe(val, "assessment", default="N/A"),
            financial_summary=fi.get("summary", "No financial data."),
            entry_ev=_safe(lbo, "entry_ev_usd", default=0),
            exit_ev=_safe(lbo, "exit_ev_usd", default=0),
            irr_base=_safe(lbo, "irr_base", default=0),
            irr_upside=_safe(lbo, "irr_upside", default=0),
            irr_downside=_safe(lbo, "irr_downside", default=0),
            moic=_safe(lbo, "moic_base", default=0),
            value_creation_levers=_bullets(fi.get("value_creation_levers", [])),
            # Risk
            risk_score=scores["risk"],
            risk_rating=ri.get("overall_risk_rating", "N/A"),
            risk_summary=ri.get("summary", "No risk data."),
            risk_protections=_bullets(ri.get("recommended_protections", [])),
            # Competitive
            competitive_score=scores["competitive"],
            market_position=co.get("market_position", "N/A"),
            competitive_summary=co.get("summary", "No competitive data."),
            competitive_advantages=_bullets(co.get("competitive_advantages", [])),
            consolidation_trend=_safe(co.get("m&a_landscape") or {}, "consolidation_trend", default="N/A"),
            recent_transactions="; ".join(((co.get("m&a_landscape") or {}).get("recent_transactions") or [])[:2]),
            # Legal
            legal_score=scores["legal"],
            legal_risk_rating=le.get("legal_risk_rating", "N/A"),
            legal_summary=le.get("summary", "No legal data."),
            deal_structure=rr.get("preferred_structure", "N/A"),
            structure_rationale=rr.get("rationale", "N/A"),
            conditions_precedent=_bullets(le.get("conditions_precedent", [])),
            close_timeline=le.get("estimated_close_timeline_months", "N/A"),
            # Score table
            w_screening  =scores["screening"]   * 0.15,
            w_financial  =scores["financial"]   * 0.30,
            w_risk       =scores["risk"]        * 0.25,
            w_competitive=scores["competitive"] * 0.20,
            w_legal      =scores["legal"]       * 0.10,
            final_rationale=final_rationale,
        )
